name: test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test-code:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: ['3.8','3.9','3.10']
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up py 
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version}}
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run py test
        run: |
          pytest --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        if: failure() && ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: htmlcov/

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."
